import { chromium } from 'playwright';
const [,, out] = process.argv;
const browser = await chromium.launch({ executablePath: process.env.PW_CHROME || '/opt/pw-browsers/chromium-1194/chrome-linux/chrome', args: ['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader', '--autoplay-policy=no-user-gesture-required'] });
const page = await browser.newPage({ viewport: { width: 960, height: 540 } });
const errs = []; page.on('pageerror', e => errs.push(e.message + ' ' + (e.stack||'').split('\n')[1]));
page.on('console', m => { if (m.type() === 'error') errs.push('console: ' + m.text()); });
await page.goto(`http://localhost:4173/?q=high`);
await page.waitForFunction(() => !document.getElementById('intro') && window.game, null, { timeout: 180000 });
// гараж: неон + блатной номер
await page.evaluate(() => { const a = window.app; a.save.data.money = 500000; a.save.setTuning('vaz2107', { neon: 1, plate: 7, horn: 1, exhaust: 1 }); a.audio.init(); a.refreshCar(); a.menus.show('garage'); a.menus.tab = 'neon'; a.menus.show('garage'); });
await page.waitForTimeout(800);
await page.screenshot({ path: `${out}/f_garage.png` });
await page.click('#daily-pill').catch(() => {});
await page.evaluate(() => window.app.menus.show('daily')); await page.waitForTimeout(200);
await page.screenshot({ path: `${out}/f_daily_menu.png` });
const r = await page.evaluate(() => { const a = window.app, g = a.game; a.startFree(true); g.renderer.setAnimationLoop(null);
  const run = (sec, ctl = {}) => { const i = g.input; const upd = i.update.bind(i); i.update = function (dt) { upd(dt); Object.assign(this, ctl); }; for (let k = 0; k < sec * 30; k++) g.tick(1/30); i.update = upd; };
  window.run = run;
  g.setTimePreset(2); g.setWeather(1); g.weather.level = 1;
  for (const id of ['hud', 'controls', 'toasts']) document.getElementById(id).classList.add('hidden');
  run(1); g.cameraRig.setMode(1); run(0.5); g.render(0);
  let pops = 0; const op = g.player.onPop; g.player.onPop = () => { pops++; op(); };
  run(3, { throttle: 1 }); run(1, { throttle: 0 });
  g.input.emit('radio'); run(1);
  return { pops, station: g.radio.station.name, daily: g.daily.tasks.map((t) => `${t.kind}:${t.progress.toFixed?.(2) ?? t.progress}/${t.goal}`).join(' '), weather: g.weather.level, plates: !!g.player.body.getObjectByName('Plates'), neon: !!g.player.neon };
});
console.log(JSON.stringify(r));
await page.evaluate(() => { const g = window.game; g.cameraRig.setMode(0); window.run(0.6, { brake: 1 }); g.render(0); });
await page.screenshot({ path: `${out}/f_rain_night.png` });
await page.evaluate(() => { const g = window.game; g.setTimePreset(0); g.cameraRig.setMode(4); window.run(1.2, { brake: 1 }); g.render(0); });
await page.screenshot({ path: `${out}/f_rain_pov.png` });
await page.evaluate(() => { const g = window.game, p = g.player.root; g.cameraRig.setMode(0); window.run(0.2, { brake: 1 }); const c = g.camera; c.position.copy(p.localToWorld(c.position.clone().set(0, 1.0, -6.5))); c.lookAt(p.localToWorld(c.position.clone().set(0, 0.6, 0))); g.render(0); });
await page.screenshot({ path: `${out}/f_plate.png` });
console.log(errs.slice(0, 10).join('\n') || 'NO ERRORS');
await browser.close();
