import { chromium } from 'playwright';
const [,, out] = process.argv;
const browser = await chromium.launch({ executablePath: process.env.PW_CHROME || '/opt/pw-browsers/chromium-1194/chrome-linux/chrome', args: ['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader'] });
const page = await browser.newPage({ viewport: { width: 960, height: 540 } });
const errs = []; page.on('pageerror', e => errs.push(e.message + ' ' + (e.stack||'').split('\n')[1]));
page.on('console', m => { if (m.type() === 'error') errs.push('console: ' + m.text()); });
await page.goto(`http://localhost:4173/?autostart&nogov&q=high&free`);
await page.waitForFunction(() => window.game && window.game.mode, null, { timeout: 180000 });
const info = await page.evaluate(() => { const g = window.game; g.renderer.setAnimationLoop(null);
  window.run = (sec, mv = {}) => { const i = g.input; const upd = i.update.bind(i); i.update = function (dt) { upd(dt); if (this.onFoot) { this.moveX = mv.x || 0; this.moveY = mv.y || 0; } }; for (let k = 0; k < sec * 30; k++) g.tick(1/30); g.render(0); i.update = upd; };
  window.run(0.5); g.input.emit('door'); window.run(0.5);
  const pts = g.shops.points; const kinds = {}; for (const p of pts) kinds[p.kind] = (kinds[p.kind] || 0) + 1;
  return { total: pts.length, kinds, kiosks: g.shops.kioskCount }; });
console.log(JSON.stringify(info));
const goTo = (kind) => page.evaluate((kind) => { const g = window.game, w = g.walker;
  const p = g.shops.points.filter((p) => p.kind === kind).sort((a, b) => Math.hypot(a.x - w.pos.x, a.z - w.pos.z) - Math.hypot(b.x - w.pos.x, b.z - w.pos.z))[0];
  w.pos.set(p.x + p.nx * 0.6, 0.15, p.z + p.nz * 0.6); w.yaw = Math.atan2(-p.nx, -p.nz);
  g.cameraRig.footYaw = Math.atan2(-p.nx, -p.nz) + 0.7; g.cameraRig.footDist = 4.2; g.cameraRig.footPitch = 0.15; g.cameraRig._footInit = false;
  window.run(0.8); return !document.getElementById('btn-shop').classList.contains('hidden'); }, kind);
console.log('kiosk btn', await goTo('kiosk'));
await page.screenshot({ path: `${out}/shop_kiosk.png` });
await page.click('#btn-shop'); await page.waitForTimeout(200);
await page.screenshot({ path: `${out}/shop_ui.png` });
const m0 = await page.evaluate(() => window.app.save.money);
await page.click('[data-k="cola"]');
await page.evaluate(() => { window.run(1.3); window.game.cameraRig.footYaw += 2.2; window.game.cameraRig.footDist = 2.4; window.run(0.4); });
await page.screenshot({ path: `${out}/shop_drink.png` });
const m1 = await page.evaluate(() => window.app.save.money);
console.log('money', m0, '->', m1, 'food', await page.evaluate(() => window.game.walker.food?.kind));
await page.evaluate(() => window.run(9));
console.log('after', await page.evaluate(() => window.game.walker.food?.kind || 'done'));
console.log('grocery btn', await goTo('grocery'));
await page.screenshot({ path: `${out}/shop_grocery.png` });
await page.click('#btn-shop'); await page.click('[data-k="sandwich"]');
await page.evaluate(() => { window.game.input.emit('sit'); window.run(2.6); window.game.cameraRig.footYaw += 2.6; window.game.cameraRig.footDist = 2.2; window.run(0.3); });
await page.screenshot({ path: `${out}/shop_eat_squat.png` });
console.log(errs.slice(0, 10).join('\n') || 'NO ERRORS');
await browser.close();
