namespace RussianDrift.Core
{
    /// <summary>RU / EN string table (key, Russian, English). Placeholders use string.Format syntax.</summary>
    public static class LocTable
    {
        public static void Fill()
        {
            Loc.Add("awards.title", "Достижения", "Achievements");
            Loc.Add("battle.difficulty", "Сложность соперника", "Rival difficulty");
            Loc.Add("battle.duration", "Дуэль {0} с", "Duel {0} s");
            Loc.Add("battle.rival", "Соперник", "Rival");
            Loc.Add("battle.you", "Ты", "You");
            Loc.Add("boot.audio", "Синтез звуков...", "Synthesising audio...");
            Loc.Add("boot.done", "Готово", "Ready");
            Loc.Add("boot.graphics", "Подбор графики под устройство...", "Tuning graphics for your device...");
            Loc.Add("boot.profile", "Загрузка профиля...", "Loading profile...");
            Loc.Add("common.back", "Назад", "Back");
            Loc.Add("common.best", "Рекорд", "Best");
            Loc.Add("common.close", "Закрыть", "Close");
            Loc.Add("common.done", "Готово", "Done");
            Loc.Add("common.failed", "Не удалось", "Failed");
            Loc.Add("common.level", "УРОВЕНЬ", "LEVEL");
            Loc.Add("common.locked", "Закрыто", "Locked");
            Loc.Add("common.reqlevel", "Нужен уровень {0}", "Requires level {0}");
            Loc.Add("common.start", "СТАРТ", "START");
            Loc.Add("daily.claim", "Забрать награду", "Claim reward");
            Loc.Add("daily.claimed", "Получено", "Claimed");
            Loc.Add("daily.claimquest", "Забрать", "Claim");
            Loc.Add("daily.day", "День {0}", "Day {0}");
            Loc.Add("daily.login", "Ежедневный бонус", "Daily login bonus");
            Loc.Add("daily.quests", "Задания дня", "Today's quests");
            Loc.Add("daily.title", "Задания и бонусы", "Daily rewards");
            Loc.Add("diff.easy", "Новичок", "Rookie");
            Loc.Add("diff.hard", "Мастер", "Expert");
            Loc.Add("diff.normal", "Любитель", "Amateur");
            Loc.Add("diff.pro", "Легенда", "Legend");
            Loc.Add("driver.cap", "Кепка", "Cap");
            Loc.Add("driver.cap1", "Чёрная", "Black");
            Loc.Add("driver.cap2", "Красная", "Red");
            Loc.Add("driver.cap3", "Синяя", "Blue");
            Loc.Add("driver.color", "Цвет одежды", "Outfit colour");
            Loc.Add("driver.gl1", "Очки", "Glasses");
            Loc.Add("driver.gl2", "Спорт", "Shades");
            Loc.Add("driver.glasses", "Очки", "Glasses");
            Loc.Add("driver.none", "Нет", "None");
            Loc.Add("driver.o0", "Куртка", "Jacket");
            Loc.Add("driver.o1", "Спорт-костюм", "Tracksuit");
            Loc.Add("driver.o2", "Футболка", "T-shirt");
            Loc.Add("driver.o3", "Худи", "Hoodie");
            Loc.Add("driver.o4", "Кожанка", "Leather");
            Loc.Add("driver.outfit", "Одежда", "Outfit");
            Loc.Add("driver.skin", "Цвет кожи", "Skin tone");
            Loc.Add("free.setup", "Свободная езда", "Free roam setup");
            Loc.Add("free.time", "Время суток", "Time of day");
            Loc.Add("free.weather", "Погода", "Weather");
            Loc.Add("garage.buy", "КУПИТЬ", "BUY");
            Loc.Add("garage.camber", "Развал колёс", "Camber");
            Loc.Add("garage.cars", "Машины", "Cars");
            Loc.Add("garage.clearance", "Клиренс (низко - высоко)", "Ride height (low - high)");
            Loc.Add("garage.drive", "Привод", "Drivetrain");
            Loc.Add("garage.driver", "Водитель", "Driver");
            Loc.Add("garage.equipped", "Установлено", "Equipped");
            Loc.Add("garage.max", "МАКС", "MAX");
            Loc.Add("garage.owned", "Куплено", "Owned");
            Loc.Add("garage.ownfirst", "Сначала купи эту машину", "Buy this car first");
            Loc.Add("garage.price", "Цена: {0}", "Price: {0}");
            Loc.Add("garage.select", "ВЫБРАТЬ", "SELECT");
            Loc.Add("garage.selected", "Выбрана", "Selected");
            Loc.Add("garage.tint", "Тонировка (0-3)", "Window tint (0-3)");
            Loc.Add("garage.tuning", "Тюнинг", "Tuning");
            Loc.Add("garage.visual", "Внешний вид", "Visual");
            Loc.Add("hud.achievement", "Достижение получено!", "Achievement unlocked!");
            Loc.Add("hud.bestlap", "Лучший круг", "Best lap");
            Loc.Add("hud.brake", "Тормоз", "Brake");
            Loc.Add("hud.bronze", "Бронза", "Bronze");
            Loc.Add("hud.cam", "Камера", "Cam");
            Loc.Add("hud.chainlost", "Цепочка потеряна  -{0}", "Chain lost  -{0}");
            Loc.Add("hud.edit.hint", "Перетаскивай кнопки. Размер - ползунком", "Drag buttons to move. Slider changes size");
            Loc.Add("hud.edit.reset", "Сброс", "Reset");
            Loc.Add("hud.firstlap", "Первый круг", "First lap");
            Loc.Add("hud.gas", "Газ", "Gas");
            Loc.Add("hud.gold", "Золото", "Gold");
            Loc.Add("hud.greatdrift", "ОТЛИЧНЫЙ ДРИФТ!", "GREAT DRIFT!");
            Loc.Add("hud.handbrake", "Ручник", "Handbrake");
            Loc.Add("hud.kick", "Сцепл.", "Kick");
            Loc.Add("hud.lap", "Круг {0}/{1}", "Lap {0}/{1}");
            Loc.Add("hud.lapdone", "Круг {0}: {1}", "Lap {0}: {1}");
            Loc.Add("hud.nearmiss", "ОПАСНЫЙ ОБГОН", "NEAR MISS");
            Loc.Add("hud.ptp", "Заезд до финиша", "Point to point");
            Loc.Add("hud.reset", "Возврат", "Reset");
            Loc.Add("hud.score", "Очки", "Score");
            Loc.Add("hud.shiftdown", "Вниз", "Down");
            Loc.Add("hud.shiftup", "Вверх", "Up");
            Loc.Add("hud.silver", "Серебро", "Silver");
            Loc.Add("hud.total", "ВСЕГО", "TOTAL");
            Loc.Add("hud.wrongway", "Не туда!", "Wrong way!");
            Loc.Add("menu.awards", "Награды", "Awards");
            Loc.Add("menu.changecar", "Сменить", "Change");
            Loc.Add("menu.daily", "Задания", "Daily");
            Loc.Add("menu.exit", "Выход", "Exit");
            Loc.Add("menu.garage", "ГАРАЖ", "GARAGE");
            Loc.Add("menu.play", "ИГРАТЬ", "PLAY");
            Loc.Add("menu.shop", "Магазин", "Shop");
            Loc.Add("menu.tagline", "Дрифт на русских тачках: от гаража до серпантина", "Drift culture, Russian style: from the garage to the mountain pass");
            Loc.Add("mode.battle", "Дрифт-баттл", "Drift battle");
            Loc.Add("mode.battle.d", "Дуэль с соперником: у кого больше очков", "Duel an AI rival: highest score wins");
            Loc.Add("mode.drift", "Дрифт-трасса", "Drift track");
            Loc.Add("mode.drift.d", "Очки за угол и скорость, зоны с бонусом", "Score by angle and speed, bonus zones");
            Loc.Add("mode.free", "Свободная езда", "Free roam");
            Loc.Add("mode.free.d", "Город, трафик, погода и никаких правил", "City, traffic, weather and no rules");
            Loc.Add("mode.ta", "Тайм-аттак", "Time attack");
            Loc.Add("mode.ta.d", "Круги и чекпоинты на лучшее время", "Laps and checkpoints against the clock");
            Loc.Add("modes.title", "Выбор режима", "Select mode");
            Loc.Add("msg.levelup", "Новый уровень: {0}!", "Level up: {0}!");
            Loc.Add("msg.lowlevel", "Недостаточно уровня", "Level too low");
            Loc.Add("msg.nomoney", "Не хватает денег", "Not enough money");
            Loc.Add("msg.tamper", "Сохранение было повреждено и восстановлено", "Save file was damaged and has been restored");
            Loc.Add("paint.hue", "Оттенок", "Hue");
            Loc.Add("paint.rimcolor", "Цвет дисков", "Rim colour");
            Loc.Add("paint.sat", "Насыщенность", "Saturation");
            Loc.Add("paint.val", "Яркость", "Brightness");
            Loc.Add("pause.exit", "В меню", "Main menu");
            Loc.Add("pause.restart", "Заново", "Restart");
            Loc.Add("pause.resume", "ПРОДОЛЖИТЬ", "RESUME");
            Loc.Add("pause.settings", "Настройки", "Settings");
            Loc.Add("pause.title", "Пауза", "Paused");
            Loc.Add("plate.allowed", "Допустимые символы: A B E K M H O P C T Y X и цифры 0-9", "Allowed: A B E K M H O P C T Y X and digits 0-9");
            Loc.Add("plate.hint", "А777АА", "A777AA");
            Loc.Add("plate.region", "Регион", "Region");
            Loc.Add("plate.text", "Номер (3 буквы + 3 цифры)", "Plate (letters and digits)");
            Loc.Add("res.avgspeed", "Средняя скорость: {0} км/ч", "Average speed: {0} km/h");
            Loc.Add("res.bestchain", "Лучший занос: {0}", "Best chain: {0}");
            Loc.Add("res.bestmult", "Макс. множитель: x{0}", "Best multiplier: x{0}");
            Loc.Add("res.coins", "монет", "coins");
            Loc.Add("res.defeat", "ПОРАЖЕНИЕ", "DEFEAT");
            Loc.Add("res.double", "Удвоить награду (реклама)", "Double reward (watch ad)");
            Loc.Add("res.finish", "ФИНИШ", "FINISH");
            Loc.Add("res.menu", "Меню", "Menu");
            Loc.Add("res.newach", "Новые достижения:", "New achievements:");
            Loc.Add("res.record", "Новый рекорд!", "New record!");
            Loc.Add("res.retry", "Ещё раз", "Retry");
            Loc.Add("res.timeup", "ВРЕМЯ ВЫШЛО", "TIME'S UP");
            Loc.Add("res.victory", "ПОБЕДА", "VICTORY");
            Loc.Add("settings.abs", "ABS", "ABS");
            Loc.Add("settings.assists", "Помощники", "Assists");
            Loc.Add("settings.audio", "Звук", "Audio");
            Loc.Add("settings.auto", "Автоматическая коробка", "Automatic gearbox");
            Loc.Add("settings.calibrate", "Калибровка наклона", "Tilt calibration");
            Loc.Add("settings.calibrate.btn", "Держу ровно", "Set neutral");
            Loc.Add("settings.cloud", "Облако", "Cloud");
            Loc.Add("settings.cloud.down", "Загрузить", "Download");
            Loc.Add("settings.cloud.sync", "Синхронизация", "Sync");
            Loc.Add("settings.cloud.up", "Отправить", "Upload");
            Loc.Add("settings.controls", "Управление", "Controls");
            Loc.Add("settings.driftassist", "Помощь в дрифте", "Drift assist");
            Loc.Add("settings.fps", "Лимит FPS", "FPS limit");
            Loc.Add("settings.graphics", "Графика", "Graphics");
            Loc.Add("settings.language", "Язык", "Language");
            Loc.Add("settings.layout", "Расположение кнопок", "Button layout");
            Loc.Add("settings.layout.btn", "Изменить", "Edit");
            Loc.Add("settings.master", "Общая громкость", "Master volume");
            Loc.Add("settings.minimap", "Мини-карта", "Mini-map");
            Loc.Add("settings.motionblur", "Размытие движения", "Motion blur");
            Loc.Add("settings.mph", "Мили в час", "Miles per hour");
            Loc.Add("settings.music", "Музыка", "Music");
            Loc.Add("settings.opacity", "Прозрачность кнопок", "Control opacity");
            Loc.Add("settings.q.auto", "Авто", "Auto");
            Loc.Add("settings.q.high", "Высокое", "High");
            Loc.Add("settings.q.low", "Низкое", "Low");
            Loc.Add("settings.q.med", "Среднее", "Medium");
            Loc.Add("settings.quality", "Качество", "Quality");
            Loc.Add("settings.scheme", "Схема управления", "Control scheme");
            Loc.Add("settings.scheme.buttons", "Кнопки", "Buttons");
            Loc.Add("settings.scheme.tilt", "Наклон", "Tilt");
            Loc.Add("settings.scheme.wheel", "Руль", "Wheel");
            Loc.Add("settings.sfx", "Эффекты", "Effects");
            Loc.Add("settings.shake", "Тряска камеры", "Camera shake");
            Loc.Add("settings.steerassist", "Помощь рулём", "Steering assist");
            Loc.Add("settings.tcs", "Антибуксовка (TCS)", "Traction control (TCS)");
            Loc.Add("settings.tiltinvert", "Инвертировать наклон", "Invert tilt");
            Loc.Add("settings.tiltsens", "Чувствительность наклона", "Tilt sensitivity");
            Loc.Add("settings.title", "Настройки", "Settings");
            Loc.Add("settings.vibration", "Вибрация", "Vibration");
            Loc.Add("shop.gotcoins", "Получено {0} монет", "Received {0} coins");
            Loc.Add("shop.restore", "Восстановить покупки", "Restore purchases");
            Loc.Add("shop.title", "Магазин", "Shop");
            Loc.Add("shop.unavailable", "Покупки недоступны в этой сборке", "Purchases are unavailable in this build");
            Loc.Add("shop.watchad", "Посмотри рекламу и получи 1 000 монет", "Watch an ad and get 1,000 coins");
            Loc.Add("shop.watchad.btn", "Смотреть", "Watch");
            Loc.Add("stat.brake", "Тормоза", "Brakes");
            Loc.Add("stat.drift", "Дрифт", "Drift");
            Loc.Add("stat.handling", "Управляемость", "Handling");
            Loc.Add("stat.power", "Мощность", "Power");
            Loc.Add("stat.speed", "Скорость", "Speed");
            Loc.Add("ta.laps", "Кругов: {0}", "Laps: {0}");
            Loc.Add("time.day", "День", "Day");
            Loc.Add("time.evening", "Вечер", "Evening");
            Loc.Add("time.morning", "Утро", "Morning");
            Loc.Add("time.night", "Ночь", "Night");
            Loc.Add("tip.0", "Совет: ручник и сброс газа помогают войти в занос", "Tip: handbrake and a lift-off help start a slide");
            Loc.Add("tip.1", "Совет: держи газ и подруливай против заноса - очки растут с углом", "Tip: hold throttle and counter-steer - points scale with angle");
            Loc.Add("tip.2", "Совет: в зонах дрифта очки умножаются", "Tip: points are multiplied inside drift zones");
            Loc.Add("tip.3", "Совет: на мокром асфальте сцепление хуже - но заносы длиннее", "Tip: wet asphalt grips less - slides get longer");
            Loc.Add("tip.4", "Совет: турбо и дифференциал в гараже сильно меняют поведение", "Tip: turbo and differential upgrades change the handling a lot");
            Loc.Add("tip.5", "Совет: кнопки на экране можно двигать в настройках", "Tip: on-screen buttons can be moved in settings");
            Loc.Add("vis.decal", "Наклейки", "Decals");
            Loc.Add("vis.kit", "Обвес", "Body kit");
            Loc.Add("vis.neon", "Неон", "Neon");
            Loc.Add("vis.paint", "Краска", "Paint");
            Loc.Add("vis.plate", "Номер", "Plate");
            Loc.Add("vis.rims", "Диски", "Rims");
            Loc.Add("vis.spoiler", "Спойлер", "Spoiler");
            Loc.Add("vis.wrap", "Плёнка", "Wrap");
            Loc.Add("weather.clear", "Ясно", "Clear");
            Loc.Add("weather.fog", "Туман", "Fog");
            Loc.Add("weather.rain", "Дождь", "Rain");
        }
    }
}
